# Generated by Django 4.2.13 on 2024-05-31 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('lastname', models.TextField(max_length=25, verbose_name='Apellido')),
                ('address', models.TextField(max_length=70, verbose_name='Dirección')),
                ('phone_number', models.TextField(max_length=16, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electrónico')),
                ('cell_number', models.TextField(max_length=16, verbose_name='Celular')),
                ('identification', models.IntegerField(max_length=11, unique=True, verbose_name='Cedula')),
                ('name_wife', models.TextField(max_length=25, verbose_name='Nombre Conyugue')),
                ('cell_number_wife', models.TextField(max_length=11, verbose_name='Celular Conyugue')),
                ('email_wife', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electrónico Conyugue')),
                ('name_children_1', models.TextField(max_length=50, verbose_name='Nombre Hijo 1')),
                ('name_children_2', models.TextField(max_length=50, verbose_name='Nombre Hijo 2')),
                ('name_children_3', models.TextField(max_length=50, verbose_name='Nombre Hijo 3')),
                ('admition_amount', models.IntegerField(default=700, verbose_name='Cuota de Admision')),
                ('aportation_certify_amount', models.IntegerField(default=500, verbose_name='Cuota de aportación')),
                ('amount_save_money', models.IntegerField(default=500, verbose_name='Cuota Mensual')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modify_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('lastname', models.TextField(max_length=25, verbose_name='Apellido')),
                ('address', models.TextField(max_length=70, verbose_name='Dirección')),
                ('phone_number', models.TextField(max_length=16, verbose_name='Telefono')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='Correo Electrónico')),
                ('cell_number', models.TextField(max_length=16, verbose_name='Celular')),
                ('identification', models.IntegerField(db_index=True, max_length=11, verbose_name='Cedula')),
                ('name_wife', models.TextField(max_length=25, verbose_name='Nombre Conyugue')),
                ('cell_number_wife', models.TextField(max_length=11, verbose_name='Celular Conyugue')),
                ('email_wife', models.EmailField(db_index=True, max_length=100, verbose_name='Correo Electrónico Conyugue')),
                ('name_children_1', models.TextField(max_length=50, verbose_name='Nombre Hijo 1')),
                ('name_children_2', models.TextField(max_length=50, verbose_name='Nombre Hijo 2')),
                ('name_children_3', models.TextField(max_length=50, verbose_name='Nombre Hijo 3')),
                ('admition_amount', models.IntegerField(default=700, verbose_name='Cuota de Admision')),
                ('aportation_certify_amount', models.IntegerField(default=500, verbose_name='Cuota de aportación')),
                ('amount_save_money', models.IntegerField(default=500, verbose_name='Cuota Mensual')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'verbose_name_plural': 'historical Clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
