# Generated by Django 4.2.13 on 2024-05-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identification',
            field=models.BigIntegerField(max_length=11, unique=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='identification',
            field=models.BigIntegerField(db_index=True, max_length=11, verbose_name='Cedula'),
        ),
    ]
