# Generated by Django 4.2.13 on 2024-05-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_identification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=70, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cell_number',
            field=models.CharField(max_length=16, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cell_number_wife',
            field=models.CharField(max_length=11, verbose_name='Celular Conyugue'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identification',
            field=models.BigIntegerField(unique=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(max_length=25, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_children_1',
            field=models.CharField(max_length=50, verbose_name='Nombre Hijo 1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_children_2',
            field=models.CharField(max_length=50, verbose_name='Nombre Hijo 2'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_children_3',
            field=models.CharField(max_length=50, verbose_name='Nombre Hijo 3'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_wife',
            field=models.CharField(max_length=25, verbose_name='Nombre Conyugue'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='address',
            field=models.CharField(max_length=70, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='cell_number',
            field=models.CharField(max_length=16, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='cell_number_wife',
            field=models.CharField(max_length=11, verbose_name='Celular Conyugue'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='identification',
            field=models.BigIntegerField(db_index=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='lastname',
            field=models.CharField(max_length=25, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='name_children_1',
            field=models.CharField(max_length=50, verbose_name='Nombre Hijo 1'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='name_children_2',
            field=models.CharField(max_length=50, verbose_name='Nombre Hijo 2'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='name_children_3',
            field=models.CharField(max_length=50, verbose_name='Nombre Hijo 3'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='name_wife',
            field=models.CharField(max_length=25, verbose_name='Nombre Conyugue'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='Telefono'),
        ),
    ]
