# Generated by Django 4.2.13 on 2024-05-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_address_alter_customer_cell_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name_children_1',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre Hijo 1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_children_2',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre Hijo 2'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_children_3',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre Hijo 3'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='name_children_1',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre Hijo 1'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='name_children_2',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre Hijo 2'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='name_children_3',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre Hijo 3'),
        ),
    ]
