# Generated by Django 4.2.13 on 2024-06-01 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0004_alter_customer_name_children_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aportation_certify_amount',
            field=models.IntegerField(default=500, verbose_name='Cuota de Aportación'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_children_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Hijo 1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_children_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Hijo 2'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_children_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Hijo 3'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='aportation_certify_amount',
            field=models.IntegerField(default=500, verbose_name='Cuota de Aportación'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='name_children_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Hijo 1'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='name_children_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Hijo 2'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='name_children_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Hijo 3'),
        ),
        migrations.CreateModel(
            name='HistoricalCustomerSaveMonth',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modify_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('amount_save_money', models.IntegerField(verbose_name='Cuota Mensual')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'historical Modelo Base',
                'verbose_name_plural': 'historical Modelos Base',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CustomerSaveMonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('amount_save_money', models.IntegerField(verbose_name='Cuota Mensual')),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
    ]
