# Generated by Django 4.2.13 on 2024-06-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customersavemonth_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersavemonth',
            name='name_customer',
            field=models.CharField(default=None, max_length=50, verbose_name='Nombre Socio'),
        ),
        migrations.AddField(
            model_name='historicalcustomersavemonth',
            name='name_customer',
            field=models.CharField(default=None, max_length=50, verbose_name='Nombre Socio'),
        ),
        migrations.AlterField(
            model_name='customersavemonth',
            name='description',
            field=models.CharField(default='Ahorro mensual', max_length=50, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='historicalcustomersavemonth',
            name='description',
            field=models.CharField(default='Ahorro mensual', max_length=50, verbose_name='Comentario'),
        ),
    ]
