# Generated by Django 4.2.13 on 2024-08-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customersavemonth_name_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Crear Socio', 'verbose_name_plural': 'Crear Socios'},
        ),
        migrations.AlterModelOptions(
            name='customersavemonth',
            options={'verbose_name': 'Ahorro Socio', 'verbose_name_plural': 'Ahorro Socios'},
        ),
        migrations.AlterModelOptions(
            name='historicalcustomer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Crear Socio', 'verbose_name_plural': 'historical Crear Socios'},
        ),
        migrations.AlterModelOptions(
            name='historicalcustomersavemonth',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Ahorro Socio', 'verbose_name_plural': 'historical Ahorro Socios'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='cell_number_wife',
            field=models.CharField(blank=True, max_length=11, verbose_name='Celular Conyugue'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_wife',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico Conyugue'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_wife',
            field=models.CharField(blank=True, max_length=25, verbose_name='Nombre Conyugue'),
        ),
        migrations.AlterField(
            model_name='customersavemonth',
            name='name_customer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre Socio'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='cell_number_wife',
            field=models.CharField(blank=True, max_length=11, verbose_name='Celular Conyugue'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='email_wife',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico Conyugue'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='name_wife',
            field=models.CharField(blank=True, max_length=25, verbose_name='Nombre Conyugue'),
        ),
        migrations.AlterField(
            model_name='historicalcustomersavemonth',
            name='name_customer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre Socio'),
        ),
    ]
